version: '3.4'

networks:
  client-server:
    driver: bridge
  postgres-server:
    driver: bridge

services:
  wid-postgres:
    image: postgres:10.4-alpine
    networks:
      - postgres-server
    environment:
      POSTGRES_DB: wid
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pass
  wid-client:
    image: ${WOLEET_ID_SERVER_REGISTRY}:client-master
    build: ./client
    ports:
      - 4220:80
    restart: on-failure
    depends_on:
      - wid-server
    networks:
      - client-server
  wid-server:
    image: ${WOLEET_ID_SERVER_REGISTRY}:server-master
    build: ./server
    restart: on-failure
    depends_on:
      - wid-postgres
    environment:
      POSTGRES_DB: wid
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pass
      POSTGRES_HOST: wid-postgres
    networks:
      - client-server
      - postgres-server
