version: '3.4'

networks:
  client-server:
    driver: bridge
  postgres-server:
    driver: bridge

services:
  wid-postgres:
    image: postgres:10.4-alpine
    networks:
      - postgres-server
    environment:
      POSTGRES_DB: wid
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pass
  wid-client:
    image: ${WOLEET_ID_SERVER_REGISTRY}:client
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${HTTP_TLS_CERTIFICATE}:/etc/nginx/ssl/certificate.crt:ro
      - ${HTTP_TLS_KEY}:/etc/nginx/ssl/certificate.key:ro
    restart: on-failure
    depends_on:
      - wid-server
    networks:
      - client-server
  wid-server:
    image: ${WOLEET_ID_SERVER_REGISTRY}:server
    restart: on-failure
    stdin_open: true
    tty: true
    depends_on:
      - wid-postgres
    environment:
      POSTGRES_DB: wid
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pass
      POSTGRES_HOST: wid-postgres
    networks:
      - client-server
      - postgres-server
