version: '3.4'

networks:
  client-server:
    driver: bridge
  postgres-server:
    driver: bridge

services:
  wid-postgres:
    image: postgres:10.4-alpine
    networks:
      - postgres-server
    environment:
      POSTGRES_DB: ${WOLEET_ID_SERVER_POSTGRES_DB:-wid}
      POSTGRES_USER: ${WOLEET_ID_SERVER_POSTGRES_USER:-pguser}
      POSTGRES_PASSWORD: ${WOLEET_ID_SERVER_POSTGRES_PASSWORD:-pass}
    volumes:
      - ${WOLEET_ID_SERVER_DATA_DIR:-./tmp}:/var/lib/postgresql/data:rw
  wid-client:
    image: ${WOLEET_ID_SERVER_REGISTRY:-woleet-id-server}:client
    build: ./client
    ports:
      - 4220:443
    volumes:
      - ${WOLEET_ID_SERVER_HTTP_TLS_CERTIFICATE:?Undefined WOLEET_ID_SERVER_HTTP_TLS_CERTIFICATE}:/etc/nginx/ssl/certificate.crt:ro
      - ${WOLEET_ID_SERVER_HTTP_TLS_KEY:?Undefined WOLEET_ID_SERVER_HTTP_TLS_KEY}:/etc/nginx/ssl/certificate.key:ro
    restart: on-failure
    depends_on:
      - wid-server
    networks:
      - client-server
  wid-server:
    image: ${WOLEET_ID_SERVER_REGISTRY:-woleet-id-server}:server
    build: ./server
    restart: on-failure
    depends_on:
      - wid-postgres
    environment:
      WOLEET_ID_SERVER_POSTGRES_DB: ${WOLEET_ID_SERVER_POSTGRES_DB:-wid}
      WOLEET_ID_SERVER_POSTGRES_USER: ${WOLEET_ID_SERVER_POSTGRES_USER:-pguser}
      WOLEET_ID_SERVER_POSTGRES_PASSWORD: ${WOLEET_ID_SERVER_POSTGRES_PASSWORD:-pass}
      WOLEET_ID_SERVER_POSTGRES_HOST: wid-postgres
    networks:
      - client-server
      - postgres-server
